#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

if (PHP_MAJOR_VERSION != 8 || PHP_MINOR_VERSION != 5) {
    echo "PHP Version Mismatch\n";
    exit(130);
}
require __DIR__ . '/vendor/autoload.php';
define('LARAVEL_START', new DateTime()->format('U.u'));
/** @var Application $app */
$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$status = $kernel->handle($input = new ArgvInput, new ConsoleOutput);
$kernel->terminate($input, $status);
exit($status);
